### ISSUE TITLE
mouse click crashes upass

### ISSUE THREAD

**Issue by 15bitgames** [Kwpolska/upass#13]
Running latest build (0.1.6) and if i click anywhere with the mouse I get the following error and it crashes.

```
[Traceback (most recent call last):
  File "/usr/bin/upass", line 11, in <module>
    sys.exit(main())
  File "/usr/lib64/python3.4/site-packages/upass/__main__.py", line 420, in main
    return App().run()
  File "/usr/lib64/python3.4/site-packages/upass/__main__.py", line 415, in run
    self.loop.run()
  File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib64/python3.4/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib64/python3.4/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib64/python3.4/site-packages/urwid/main_loop.py", line 500, in process_input
    event, button, col, row, focus=True ):
  File "/usr/lib64/python3.4/site-packages/urwid/container.py", line 1169, in mouse_event
    event, button, col, row-htrim, focus )
  File "/usr/lib64/python3.4/site-packages/upass/__main__.py", line 124, in mouse_event
    if newfocus < 0:
TypeError: unorderable types: NoneType() < int()
]
```

**Comment by Kwpolska** [comment]
Thanks! I’ll release v0.1.7 tomorrow.

**Comment by 15bitgames** [comment]
Cheers :)
