### ISSUE TITLE
Upass crashes when copy/pasting

### ISSUE THREAD

**Issue by 15bitgames** [Kwpolska/upass#15]
So I haven't changed anything regarding my environment with UPass but lately it just crashes when trying to copy/paste.  I have both xsel and xclip installed on my machine.  Here is the traceback for you.

```
Traceback (most recent call last):
  File "/usr/bin/upass", line 9, in <module>
    load_entry_point('upass==0.1.7', 'console_scripts', 'upass')()
  File "/usr/lib/python3.5/site-packages/upass/__main__.py", line 421, in main
    return App().run()
  File "/usr/lib/python3.5/site-packages/upass/__main__.py", line 416, in run
    self.loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.5/site-packages/upass/__main__.py", line 111, in keypress
    return super(FancyListBox, self).keypress(size, key)
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 985, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python3.5/site-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3.5/site-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.5/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.5/site-packages/upass/__main__.py", line 379, in call_pass
    pyperclip.copy(copytarget)
  File "/usr/lib/python3.5/site-packages/pyperclip/clipboards.py", line 125, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.exceptions.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.org 

```

**Comment by Kwpolska** [comment]
This seems to be an issue with `pyperclip` and your PATH. In the context of your Python context, running `which` fails. Try, in a `python3.5` console:

``` py
import subprocess
subprocess.call(["which", "xclip"])
subprocess.call(["which", "xsel"])
```

**Comment by Kwpolska** [comment]
Are you still experiencing issues? The copy-paste feature requires (on Linux) one of those:
- xclip
- xsel
- pyqt4
- pygtk
- klipper (kde)

**Comment by Kwpolska** [comment]
Closed due to no response for over a year.
