### ISSUE TITLE
Error when I try to run upass

### ISSUE THREAD

**Issue by slackhead** [Kwpolska/upass#19]
I've just installed upass 2.0
When I press any key at all in the terminal it crashes:

Traceback (most recent call last):
  File "/usr/bin/upass", line 11, in <module>
    load_entry_point('upass==0.2.0', 'console_scripts', 'upass')()
  File "/usr/lib64/python3.6/site-packages/upass/__main__.py", line 490, in main
    return App().run()
  File "/usr/lib64/python3.6/site-packages/upass/__main__.py", line 485, in run
    self.loop.run()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib64/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib64/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib64/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib64/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib64/python3.6/site-packages/upass/__main__.py", line 106, in keypress
    currentfocus = self.focus_position
  File "/usr/lib64/python3.6/site-packages/urwid/listbox.py", line 591, in _get_focus_position
    raise IndexError("No focus_position, ListBox is empty")
IndexError: No focus_position, ListBox is empty

**Comment by Kwpolska** [comment]
This happened because of an edge case: you had `.git` in your password store, but no other passwords, so there was nothing to show.  Released v0.2.1 with a fix.

(upass is still a read-only browser, sorry for that)

**Comment by slackhead** [comment]
Eh?

ls -la                                                   
total 40K
drwxr-xr-x   2 david users 4.0K 2017-12-24 12:14 ./
drwx--x--x 317 david users  28K 2017-12-24 13:43 ../
-rw-------   1 david users   17 2017-12-24 12:14 .gpg-id

**Comment by Kwpolska** [comment]
Well, I guessed wrong, but `.gpg-id` is still a dotfile, which means you have no other passwords.
