### ISSUE TITLE
Error  while running on windows with python 2.7

### ISSUE THREAD

**Issue by spapas** [Kwpolska/upass#21]
I am getting the following error after I install upass:

```
Traceback (most recent call last):
  File "c:\progr\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\progr\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\progr\python27\scripts\upass.exe\__main__.py", line 5, in <module>
  File "c:\progr\python27\lib\site-packages\upass\__init__.py", line 80, in <module>
    config.read_string(pkg_resources.resource_string(
AttributeError: ConfigParser instance has no attribute 'read_string'
```

**Comment by Kwpolska** [comment]
Works for me. Make sure you’ve got a recent enough version of `configparser` installed from pip, and that you don’t shadow the name with anything else.

(I should also drop legacy Python compatibility for upass one day.)
