### ISSUE TITLE
Crash on empty .password-store

### ISSUE THREAD

**Issue by pinpox** [Kwpolska/upass#5]
Opened upass with empty password-store, pressed enter.

```
binaryplease➜~(master✗)» upass                                                                                                                                                                           [20:19:40]
Traceback (most recent call last):
  File "/usr/bin/upass", line 9, in <module>
    load_entry_point('upass==0.1.4', 'console_scripts', 'upass')()
  File "/usr/lib/python3.5/site-packages/upass/__main__.py", line 414, in main
    App().run()
  File "/usr/lib/python3.5/site-packages/upass/__main__.py", line 409, in run
    self.loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.5/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.5/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.5/site-packages/upass/__main__.py", line 94, in keypress
    currentfocus = self.focus_position
  File "/usr/lib/python3.5/site-packages/urwid/listbox.py", line 591, in _get_focus_position
    raise IndexError("No focus_position, ListBox is empty")
IndexError: No focus_position, ListBox is empty

```

**Comment by Kwpolska** [comment]
Since upass is a read-only browser, we expect passwords to already exist. I added a warning on startup if the store is empty/does not exist.
